import numpy as np

class AerodynamicsSolver:
    def __init__(self, rho=1.225, x_0_hat=0.0):
        """
        Blade Element Theory solver using Mao 2024 empirical formulas for Carbon Fiber wings.
        """
        self.rho = rho
        
        # Structural Physics Parameters
        self.x_0_hat = x_0_hat # Pitch axis offset (0 to 1)

    def solve_wing_forces(self, strips, flap_vector):
        """
        Calculates quasi-steady aerodynamic forces on each wing strip.
        Applies Translational Circulation, Rotational Circulation, and updates the local strip wrench.
        """
        flap_rate = flap_vector[1]
        flap_accel = flap_vector[2] if len(flap_vector) > 2 else 0.0

        for strip in strips:
            vel = strip.pull_airspeed  # [v_x, v_y, v_z]
            
            # Local Flow Velocity in XZ plane (Assuming forward flight dominates X, flap dominates Z)
            # Add small epsilon to prevent div by zero
            v_in_sq = vel[0]**2 + vel[2]**2 + 1e-6
            v_mag = np.sqrt(v_in_sq)
            
            # Local Angle of Attack (alpha_e)
            # Our structural frame: +X is Forward (Leading Edge), +Z is Down.
            # Flow from the front (-vel[0]) and flow from below (-vel[2]) create a positive AoA.
            alpha_e = np.arctan2(-vel[2], -vel[0])
            
            # --- 1. Translational Circulation Force (Mao 2024 Eq 2 & 3) ---
            # These empirical equations yield the Normal (C_L) and Tangential (C_D) coefficients.
            C_L = 1.870 * np.sin(1.872 * alpha_e)
            C_D = 1.667 - 1.585 * np.cos(1.968 * alpha_e)
            dS = strip.chord * strip.strip_width
            q_dyn = 0.5 * self.rho * v_in_sq * dS
            
            # Normal force acts along the local Z axis.
            # Positive AoA generates lift in the -Z direction (UP).
            F_tran_z = -q_dyn * C_L
            
            # Tangential force acts along the local X axis, opposing the tangential air velocity.
            F_tran_x = np.sign(vel[0]) * q_dyn * C_D
            
            # --- 2. Rotational Circulation Force (Mao 2024 Eq 4 & 6) ---
            C_rot = 2.0 * np.pi * (0.75 - self.x_0_hat)
            # Force generated by the wing angularly sweeping through the air.
            # Because we do not have active pitching motion (alpha_dot = 0), this is 0.
            F_rot_z = 0.0
            
            # --- 3. Added Mass Force (Mao 2024 Eq 7 simplified) ---
            # Approximating the mass of the air cylinder accelerated by the wing.
            # Since our wing is horizontal and flaps vertically, the normal is aligned with the acceleration.
            # Added Mass inherently opposes the acceleration.
            F_add_z = -0.25 * np.pi * self.rho * (strip.chord**2) * (flap_accel * strip.y_offset) * strip.strip_width
            
            # --- 4. Wing Structural Inertial Force (Mao 2024 Eq 8 & Eq 23) ---
            # Inertial force opposes the acceleration of the localized mass of the strips CF rods and cellophane
            F_iner_z = -strip.strip_mass * (flap_accel * strip.y_offset)
            
            # --- Total Force Assignment ---
            # Sum forces and apply to local strip center of pressure
            F_tot_x = F_tran_x
            F_tot_y = 0.0
            F_tot_z = F_tran_z + F_rot_z + F_add_z + F_iner_z
            
            # Pitching Moment (Local My) from CoP offset
            # CoP is relative to leading edge
            M_pitch = F_tot_z * strip.chordwise_cop
            
            # Update the strip's internal wrench
            wrench = np.array([F_tot_x, F_tot_y, F_tot_z, 0.0, M_pitch, 0.0])
            strip.push_wrench(wrench)

    def solve_tail_forces(self, tailcop):
        """
        Calculates simple flat-plate aerodynamics for the tail control surface.
        """
        vel = tailcop.pull_airspeed
        
        v_in_sq = vel[0]**2 + vel[2]**2 + 1e-6
        alpha = np.arctan2(-vel[2], -vel[0])
        
        # Standard flat plate formulas
        C_L = 2 * np.pi * alpha
        C_D = 1.28 * np.sin(alpha)**2 + 0.05
        
        # Assume generic small tail area
        dS = 0.05 
        q_dyn = 0.5 * self.rho * v_in_sq * dS
        
        F_z = -q_dyn * C_L
        F_x = np.sign(vel[0]) * q_dyn * C_D
        
        wrench = np.array([F_x, 0.0, F_z, 0.0, 0.0, 0.0])
        tailcop.push_wrench(wrench)
