import numpy as np

class AerodynamicsSolver:
    def __init__(self, rho=1.225, x_0_hat=0.0):
        """
        Blade Element Theory solver using Mao 2024 empirical formulas for Carbon Fiber wings.
        """
        self.rho = rho
        
        # Structural Physics Parameters
        self.x_0_hat = x_0_hat # Pitch axis offset (0 to 1)

    def solve_wing_forces(self, strips, flap_vector):
        """
        Calculates quasi-steady aerodynamic forces on each wing strip.
        Applies Translational Circulation, Rotational Circulation, and updates the local strip wrench.
        """
        flap_rate = flap_vector[1]
        flap_accel = flap_vector[2] if len(flap_vector) > 2 else 0.0

        for strip in strips:
            vel = strip.pull_airspeed  # [v_x, v_y, v_z]
            
            # Local Flow Velocity in XZ plane (Assuming forward flight dominates X, flap dominates Z)
            # Add small epsilon to prevent div by zero
            v_in_sq = vel[0]**2 + vel[2]**2 + 1e-6
            v_mag = np.sqrt(v_in_sq)
            
            # Absolute Angle of Attack (magnitude) to keep C_L and C_D positive
            alpha_mag = np.arctan2(np.abs(vel[2]), np.abs(vel[0]))
            
            # --- 1. Translational Circulation Force (Mao 2024 Eq 2 & 3) ---
            # These empirical equations yield the Lift (C_L) and Drag (C_D) relative to airflow.
            C_L = 1.870 * np.sin(1.872 * alpha_mag)
            
            # Added 1.2 parasitic drag (C_D0) to significantly lower the trim velocity to 6 m/s
            C_D = 1.667 - 1.585 * np.cos(1.968 * alpha_mag) + 1.2
            dS = strip.chord * strip.strip_width
            q_dyn = 0.5 * self.rho * v_in_sq * dS
            
            # Convert to Normal (C_N) and Tangential (C_T) coefficients
            C_N = C_D * np.sin(alpha_mag) + C_L * np.cos(alpha_mag)
            C_T_friction = C_D * np.cos(alpha_mag)
            C_T_suction = C_L * np.sin(alpha_mag)
            
            # --- AEROELASTIC TWIST EFFICIENCY FACTOR ---
            # Mao 2024 uses a full structural deformation solver to calculate how the cellophane twists.
            # Because our simulator is rigid-body, we apply an empirical efficiency factor to 
            # simulate the air "spilling" off the flexible wing, bringing the rigid force down to ~12N.
            efficiency = 0.15 
            C_N *= efficiency
            C_T_friction *= efficiency
            C_T_suction *= efficiency
            
            # Normal force acts along the local Z axis.
            # Opposes vertical flow (if air from below, vel[2] < 0, Force pushes UP / -Z)
            F_tran_z = C_N * q_dyn * np.sign(vel[2])
            
            # Tangential force acts along the local X axis.
            # Friction opposes horizontal airflow. Suction ALWAYS pulls towards Leading Edge (+X).
            F_tran_x = (C_T_friction * q_dyn * np.sign(vel[0])) + (C_T_suction * q_dyn * 1.0)
            
            # --- 2. Rotational Circulation Force (Mao 2024 Eq 4 & 6) ---
            C_rot = 2.0 * np.pi * (0.75 - self.x_0_hat)
            # Force generated by the wing angularly sweeping through the air.
            # Because we do not have active pitching motion (alpha_dot = 0), this is 0.
            F_rot_z = 0.0
            
            # --- 3. Added Mass Force (Mao 2024 Eq 7 simplified) ---
            # Approximating the mass of the air cylinder accelerated by the wing.
            # Since our wing is horizontal and flaps vertically, the normal is aligned with the acceleration.
            # Added Mass inherently opposes the acceleration.
            F_add_z = -0.25 * np.pi * self.rho * (strip.chord**2) * (flap_accel * strip.y_offset) * strip.strip_width
            
            # --- 4. Wing Structural Inertial Force (Mao 2024 Eq 8 & Eq 23) ---
            # Inertial force opposes the acceleration of the localized mass of the strips CF rods and cellophane
            F_iner_z = -strip.strip_mass * (flap_accel * strip.y_offset)
            
            # --- Total Force Assignment ---
            # Sum forces and apply to local strip center of pressure
            F_tot_x = F_tran_x
            F_tot_y = 0.0
            F_tot_z = F_tran_z + F_rot_z + F_add_z + F_iner_z
            
            # Pitching Moment (Local My) from CoP offset
            # CoP is relative to leading edge
            M_pitch = F_tot_z * strip.chordwise_cop
            
            # Update the strip's internal wrench
            wrench = np.array([F_tot_x, F_tot_y, F_tot_z, 0.0, M_pitch, 0.0])
            strip.push_wrench(wrench)

    def solve_body_forces(self, body):
        
        # Calculate Body Drag to prevent unrealistic infinite acceleration
        vel = body.pull_airspeed
        v_in_sq = vel[0]**2 + vel[1]**2 + vel[2]**2 + 1e-6
        v_mag = np.sqrt(v_in_sq)
        
        # Increased body drag area and coefficient to match 6 m/s trim speed
        Cd_body = 1.2
        A_body = 0.10 # 0.10 m^2 frontal area
        
        q_dyn = 0.5 * self.rho * v_in_sq * A_body
        
        # Drag acts in the direction of the airflow (vel)
        u_flow = vel / v_mag
        F_drag_vec = (q_dyn * Cd_body) * u_flow
        
        wrench = np.zeros(6)
        wrench[:3] = F_drag_vec
        
        body.push_wrench(wrench)

    def solve_tail_forces(self, tailcop):
        """
        Calculates simple flat-plate aerodynamics for the tail control surface.
        """
        vel = tailcop.pull_airspeed
        
        v_in_sq = vel[0]**2 + vel[2]**2 + 1e-6
        alpha_mag = np.arctan2(np.abs(vel[2]), np.abs(vel[0]))
        
        # Standard flat plate formulas
        C_L = 2 * np.pi * alpha_mag
        C_D = 1.28 * np.sin(alpha_mag)**2 + 0.05
        
        # Assume generic small tail area
        dS = 0.05 
        q_dyn = 0.5 * self.rho * v_in_sq * dS
        
        # Convert to Normal (C_N) and Tangential (C_T) coefficients
        C_N = C_D * np.sin(alpha_mag) + C_L * np.cos(alpha_mag)
        C_T_friction = C_D * np.cos(alpha_mag)
        C_T_suction = C_L * np.sin(alpha_mag)
        
        F_z = C_N * q_dyn * np.sign(vel[2])
        F_x = (C_T_friction * q_dyn * np.sign(vel[0])) + (C_T_suction * q_dyn * 1.0)
        
        wrench = np.array([F_x, 0.0, F_z, 0.0, 0.0, 0.0])
        tailcop.push_wrench(wrench)
