import json
import os

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Flapping Wing UAV - Flight Data Analysis\n",
    "This notebook analyzes the physical telemetry generated by the `SimulationLogger`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import os\n",
    "\n",
    "# Set up plotting directory\n",
    "os.makedirs('../plot', exist_ok=True)\n",
    "\n",
    "# Load Simulation Data\n",
    "csv_path = '../plot/simulation_data.csv'\n",
    "df = pd.read_csv(csv_path)\n",
    "print(f\"Loaded {len(df)} time steps of flight data.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 1. Actuation vs Aerodynamic Lift & Thrust\n",
    "Correlating the instantaneous flapping angle with the resulting Z-axis lift and X-axis thrust."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig, ax1 = plt.subplots(figsize=(10, 5))\n",
    "\n",
    "color = 'tab:blue'\n",
    "ax1.set_xlabel('Time (s)')\n",
    "ax1.set_ylabel('Flap Angle (rad)', color=color)\n",
    "ax1.plot(df['time'], df['flap_angle'], color=color, label='Flap Angle')\n",
    "ax1.tick_params(axis='y', labelcolor=color)\n",
    "\n",
    "ax2 = ax1.twinx()\n",
    "color = 'tab:red'\n",
    "ax2.set_ylabel('Force (N)', color=color)\n",
    "ax2.plot(df['time'], df['force_z'], color='tab:red', linestyle='--', label='Lift (Z)')\n",
    "ax2.plot(df['time'], df['force_x'], color='tab:green', linestyle=':', label='Thrust (X)')\n",
    "ax2.tick_params(axis='y', labelcolor=color)\n",
    "\n",
    "fig.tight_layout()\n",
    "plt.title(\"Actuation vs Aerodynamics\")\n",
    "fig.legend(loc=\"upper right\", bbox_to_anchor=(1,1), bbox_transform=ax1.transAxes)\n",
    "plt.savefig('../plot/actuation_forces.png')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. 3D Flight Trajectory\n",
    "Visualizing the spatial path of the drone's center of mass."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "fig = plt.figure(figsize=(10, 8))\n",
    "ax = fig.add_subplot(111, projection='3d')\n",
    "\n",
    "ax.plot(df['pos_x'], df['pos_y'], df['pos_z'], label='Flight Path', linewidth=2, color='purple')\n",
    "ax.scatter(df['pos_x'].iloc[0], df['pos_y'].iloc[0], df['pos_z'].iloc[0], color='green', s=100, label='Start')\n",
    "ax.scatter(df['pos_x'].iloc[-1], df['pos_y'].iloc[-1], df['pos_z'].iloc[-1], color='red', s=100, label='End')\n",
    "\n",
    "ax.set_xlabel('X (m)')\n",
    "ax.set_ylabel('Y (m)')\n",
    "ax.set_zlabel('Z (m)')\n",
    "ax.set_title('3D Flight Trajectory')\n",
    "ax.legend()\n",
    "plt.savefig('../plot/3d_trajectory.png')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Velocity Over Time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(10, 5))\n",
    "plt.plot(df['time'], df['vel_x'], label='Vx (Forward)', color='green')\n",
    "plt.plot(df['time'], df['vel_y'], label='Vy (Lateral)', color='orange')\n",
    "plt.plot(df['time'], df['vel_z'], label='Vz (Vertical)', color='blue')\n",
    "plt.xlabel('Time (s)')\n",
    "plt.ylabel('Velocity (m/s)')\n",
    "plt.title('Body Velocities')\n",
    "plt.legend()\n",
    "plt.grid()\n",
    "plt.savefig('../plot/body_velocities.png')\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("output/flight_analysis.ipynb", "w") as f:
    json.dump(notebook_content, f, indent=1)

print("Created output/flight_analysis.ipynb successfully.")
